#置換結果をリアルタイム表示
[[plugins]]
repo = 'markonm/traces.vim'

#ds( ()を削除
#cs({ ()を{}に変更
#ysiw( 単語を()で囲む
#S( Visualモードの選択範囲を()で囲む
[[plugins]]
repo = 'tpope/vim-surround'

#vim-surroundをドットでリピートできるようにする
[[plugins]]
repo = 'tpope/vim-repeat'

#text objectを自己定義
[[plugins]]
repo = 'kana/vim-textobj-user'

#ie or aeで全体
[[plugins]]
repo = 'kana/vim-textobj-entire'

#ilで前後の空白含まない1行
#alで前後の空白含む1行
#改行文字を含めないことで差別化
[[plugins]]
repo = 'kana/vim-textobj-line'

#iFで関数の中身
#aFで関数全体
#init.vimで再定義中
[[plugins]]
repo = 'kana/vim-textobj-function'
hook_add='''
omap iF <Plug>(textobj-function-i)
omap aF <Plug>(textobj-function-a)
vmap iF <Plug>(textobj-function-i)
vmap aF <Plug>(textobj-function-a)
'''

#iu or auでURL
[[plugins]]
repo = 'mattn/vim-textobj-url'

#任意の一文字の間
#if~で~~の中身など
#af~で~~を含めた全体など
[[plugins]]
repo = 'thinca/vim-textobj-between'

#icでコメント内部
#acでコメント全体
[[plugins]]
repo = 'thinca/vim-textobj-comment'

#i-で--の中身
#a-で--を含めた全体
[[plugins]]
repo = 'RyanMcG/vim-textobj-dash'

#irrでRubyのブロック内部
#arrでRubyのブロック全体
[[plutins]]
repo = 'rhysd/vim-textobj-ruby'

#i,wでキャメルケース、スネークケース等の単語内単語
[[plugins]]
repo = 'h1mesuke/textobj-wiw'

#ix[でarr[i]のi
#ax[でarr[i]全体
[[plugins]]
repo = 'anyakichi/vim-textobj-xbrackets'

#i.で引数1つ
#a.で引数1つと次の区切り文字
[[plugins]]
repo = 'sgur/vim-textobj-parameter'
hook_add = '''
let g:vim_textobj_parameter_mapping = '.'
'''

#operatorを追加定義
[[plugins]]
repo = 'kana/vim-operator-user'

#Rでレジスタの中身と入れ替え
[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add='''
nmap R <Plug>(operator-replace)
nmap R <Plug>(operator-replace)
'''

#URLをブラウザで開くなど previmとの連携もある
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add='''
let g:netrw_nogx = 1
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
'''

#ヘルプの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

#コメントトグラー
[[plugins]]
repo = 'tpope/vim-commentary'
